direction: right
Python3.style.font-color: lightblue
Pascal.style.font-color: orange
C++.style.font-color: Blue
C-sharp.style.font-color: "#BF40BF"
Java.style.font-color: red
Languages
Languages -> Python3
Languages -> Pascal
Languages -> C++
Languages -> C-sharp
Languages -> Java
Tables.style.font-color: lightgreen
Tasks
Tasks -> Search for Symbols (10)
Tasks -> Programming
Programming -> Boolean tables (2)
Programming -> Execution of Algorithms (12)
Programming -> Boolean Expressions Evalution (15)
Programming -> Recursive Algorithms (16)
Programming -> Number Sequence Proecssing (17)
Programming -> Best Strategy
Best Strategy -> 1 (19)
Best Strategy -> 2 (20)
Best Strategy -> 3 (21)
Programming -> Branching and Bruteforcing (23)
Programming -> Symbol Lines Processing (24)
Programming -> Integer Processing
Integer Processing -> 1 (25)
Integer Processing -> 2 (26)
Programming -> Programming (27)
Tasks -> Tables
Tables -> Tables (9)
Tables -> Relational Databases (3)
Tables -> Robot Money Collector (18)
Tasks -> Paper (mathematics)
Paper (mathematics) -> Graphs (1)
Paper (mathematics) -> Coding and Encoding Information (4)
Paper (mathematics) -> Result of Simple Algorithms (6)
Paper (mathematics) -> Transmitting Data (7)
Paper (mathematics) -> Number Systems and Bust (8)
Paper (mathematics) -> Volume of Information (11)
Paper (mathematics) -> Computer Networks (13)
Paper (mathematics) -> Number Systems and Number Encoding (14)
