tasks
simple
middle
hard
tasks -> simple
tasks -> middle
tasks -> hard
Probability Theory: {
  4_simple probability theory
  5_complex probability theory
}
Text Problems: {9; 10}
Simple Count Tasks: {6; 7}
Analysis: {8; 11; 12}

simple -> Probability Theory
simple -> Text Problems
simple -> Simple Count Tasks
middle -> finance mathematics
middle -> stereometry
middle -> equations
hard -> analysis
hard -> parameter
hard -> number theory
hard -> planimetry
